### ISSUE TITLE
Complete charts in the readme

### ISSUE THREAD

**Issue by jbkunst** [jsdeherrera/prioritizationMatrix#1]
Hi @jsdeherrera 

In your `readme.Rmd` you can modify the chunk options at the beginning of the file to allow webshot wait until the chart is displayed completely before make the screenshot :wink: 

```r
knitr::opts_chunk$set(echo = TRUE, screenshot.opts = list(delay = 5))
```

**Comment by jordandeherrera** [comment]
Thanks, @jbkunst!  I really appreciate the tip.  Also, I'm a HUGE fan of your work.  Thanks so much for the highcharter package!
